import { useState } from 'react';
import { useWorkflowStore } from '../../store/workflowStore';
import { Sparkles, ArrowRight, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import type { WorkflowNode, WorkflowEdge } from '../../types/workflow';

export function AICopilot() {
  const [prompt, setPrompt] = useState('');
  const [generating, setGenerating] = useState(false);
  const { setNodes, setEdges } = useWorkflowStore();

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setGenerating(true);
    try {
      const response = await fetch('/api/copilot/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });
      
      if (!response.ok) throw new Error('Generation failed');
      
      const data = (await response.json()) as { nodes: WorkflowNode[]; edges: WorkflowEdge[] };
      
      // The API should return the fully formed graph. We replace the current canvas.
      if (data.nodes.length > 0) {
        setNodes(data.nodes);
        setEdges(data.edges);
        toast.success('Pipeline auto-generated by AI');
        setPrompt('');
      } else {
        toast.error('AI could not understand the prompt');
      }
    } catch (error) {
      console.error(error);
      toast.error('Failed to communicate with Copilot Engine');
    } finally {
      setGenerating(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleGenerate();
    }
  };

  return (
    <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-50 w-[500px] max-w-[90vw]">
      <div className="relative group">
        {/* Glow effect behind the input */}
        <div className="absolute -inset-1 bg-gradient-to-r from-violet-600 via-fuchsia-600 to-sky-600 rounded-full blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
        
        {/* Input container */}
        <div className="relative bg-[#1a1a2e]/90 backdrop-blur-md border border-white/10 rounded-full flex items-center p-2 shadow-2xl">
          <div className="pl-3 pr-2 text-violet-400">
            {generating ? (
              <Loader2 size={20} className="animate-spin" />
            ) : (
              <Sparkles size={20} />
            )}
          </div>
          
          <input
            type="text"
            className="flex-1 bg-transparent border-none text-white text-sm placeholder-white/30 focus:outline-none focus:ring-0 px-2 py-1.5"
            placeholder="E.g. send a slack message then create a Jira ticket..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={generating}
          />
          
          <button
            onClick={handleGenerate}
            disabled={generating || !prompt.trim()}
            className="bg-violet-600 hover:bg-violet-500 disabled:bg-white/5 disabled:text-white/30 disabled:cursor-not-allowed text-white rounded-full p-2 ml-2 transition-colors flex items-center justify-center"
          >
            <ArrowRight size={16} />
          </button>
        </div>
      </div>
      
      {/* Floating hint label */}
      <div className="text-center mt-3">
        <span className="text-[10px] font-medium tracking-widest uppercase text-white/40 bg-black/40 backdrop-blur-sm px-3 py-1 rounded-full border border-white/5">
          AI Workflow Copilot
        </span>
      </div>
    </div>
  );
}
